# Generated by Django 5.0.14 on 2026-07-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_readchapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='flag',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
