# Generated by Django 5.0.14 on 2026-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_discussiongroup_groupmessage_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
